Issue 92
deepdoctection/deepdoctection pull request #102
Opened 2022-12-27 08:43 UTC by LightAllWorld

This PR fixes issue #92 :

It adds an setter `set_tesseract_path` about tesseract path.

2022-12-27 18:54 UTC, JaMe76 commented on deepdoctection/utils/file_utils.py
> +    global _TESS_AVAILABLE
Please add a short docstring, e.g. what path to add for installation with Anaconda

2022-12-27 18:56 UTC, JaMe76 commented on deepdoctection/utils/file_utils.py
> +def set_tesseract_path(tesseract_path: str="tesseract"):
function will need a typing return statement:

```
set_tesseract_path(tesseract_path: str="tesseract") -> None:
```

2022-12-27 19:21 UTC, JaMe76 requested changes
Thanks for your PR!

1.) To make the PATH changes to tesseract effective in predictions _TESS_PATH needs to be imported to `extern.tessocr` and _TESS_PATH must replace "tesseract" in line 96. 

```
cmd_args += ("tesseract", input_file_name, output_file_name_base, "-l", lang)
```

2.) Can you add `set_tesseract_path` to `deepdoctection.__init__.py`  in _IMPORT_STRUCTURE dict in line 265? All modules are imported in a lazy manner, so not adding this function here would result in import error when invoked.   

3.) I've added some small remarks in your changes. 

Once merged, I would convert the original issue into the discussion section so users from Anaconda installs do not need to dig into closed issues. 

Thanks

2022-12-28 04:53 UTC, LightAllWorld commented
Thanks for your comments.

1. Added doc strings about `set_tesserect_path` and `_TESS_PATH'.

2. Replaced extern.tessocr's "tesserect" in line 96.

3. Add `set_tesseract_path' to `deepdoctection.__init__.py` in 265 line.

2022-12-28 09:21 UTC, JaMe76 approved these changes
Thanks for your updates. 

Will be merged.

2022-12-28 15:47 UTC, merged